### ISSUE TITLE
Sliders lag the game a lot

### ISSUE THREAD

**Issue by ibmoth** [Rodrig0v/osumaniaidle#2]
I don't know if this is just my hardware that's terrible, but I can run the songs fine until there's a few sliders in a short period of time. I can't give a video showing it but an example is the beatmap [4orce!](https://osu.ppy.sh/beatmapsets/1317226) near the beginning. Thanks ✅

**Comment by EduardoTheSport** [comment]
@BMOTheGhost Set your FPS cap to 75, it makes it not laggy at least for me.

**Comment by ibmoth** [comment]
alright thanks
